### ISSUE TITLE
Uneven grid distribution in `People` Page

### ISSUE THREAD

**Issue by Sweetdevil144** [PecanProject/web#34]
I noticed several non uniform grid distributions in the page `peoples.js` which rendered image cards mainly on the basis of provided URLs in `contributors.js`. Is there any way we can modify the grid distribution to reduce gaps and improve the UI ?
Following are some views I found odd for the UI : 
<img width="540" alt="Screenshot 2024-01-02 at 11 45 25 AM" src="https://github.com/PecanProject/web/assets/117591942/76c7594b-a3d8-4c38-9b3f-a945da282e96">
<img width="540" alt="Screenshot 2024-01-02 at 11 45 13 AM" src="https://github.com/PecanProject/web/assets/117591942/528637dd-a5bf-46c1-9634-25145652918f">

**Comment by Sweetdevil144** [comment]
In the first image, Card on the left is rendered small, whereas the Card on the right occupies more spacing due to which an uneven gap is produced. Same goes to say for the second image also.

**Comment by Sweetdevil144** [comment]
If their is a grid layout being used somehow, then we can leverage CSS Grid Layout to provide a more uniform and flexible grid. This will allow us to handle cards of varying content sizes gracefully and ensure consistent gaps and alignments as shown below :
```css
.peopleContainer {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  grid-gap: 20px;
  align-items: start;
}

.card {
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  height: 100%;
}
```

With grid-template-columns, we're defining a responsive grid that adjusts the number of columns based on the card size and the available space. minmax(250px, 1fr) ensures that cards can scale between 250px and the fraction of available space, maintaining consistency across different screen sizes.

grid-gap provides consistent spacing between grid items, and align-items: start aligns grid items to the start of the grid area, which makes the top alignment consistent.

I would love to get your thoughts on this approach. If anyone has suggestions or improvements, please share!

**Comment by RohanSasne** [comment]
Nice catch @Sweetdevil144 , can you come up with a PR for the same?

**Comment by Sweetdevil144** [comment]
Yeah sure! I'll create a PR for the same. If I face any problem then I'll surely contact you over here or on Slack discussion threads.

**Comment by Sweetdevil144** [comment]
> We can also use card animation to improve the UI 

Yeah sure we can. But right now I'm trying to focus mainly on improving the grid view instead. If I find time I'll add some css animations too. I believe the following animation would suit perfect :
```css
.card-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
    grid-gap: 20px;
}

.card {
    background: #f3f3f3;
    padding: 20px;
    text-align: center;
    transition: transform 0.3s ease-in-out;
}

.card:hover {
    transform: scale(1.1); /* Enlarges the card to 110% of its original size */
}
```
